name: Deploy To Local Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[deploy]') || contains(github.event.head_commit.message, '[major]')
    runs-on: [self-hosted, linux, zefix]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make deploy script executable
        run: chmod +x ./deploy.sh

      - name: Deploy
        run: ./deploy.sh